### PR TITLE
Find services by regex

### PR DESCRIPTION
**Pull request by ArthurHlt**
Now we can find service by giving a regex when searching:
- By tag
- By name

I add a function `FirstWithName` to replace `WithName` function which now gives an array of service.

### CODE REVIEW

**Comment by drnic** [comment]
I'd prefer we didn't change the API. Can we keep the semantics of the `WithName` function and add a newly named function with the new behavior? Then users won't have surprises.

**Comment by joefitzgerald** [comment]
:+1: on @drnic's suggestion. Perhaps we call the new function `UsingPattern` or `UsingRegex` (or anything similar). I'd also prefer they we have functions for Tag and Name rather than conflating them.

**Comment by ArthurHlt** [comment]
I agree with both of you. I'm making the changes.
Now, `WithTag` and `WithName` will be like before and my changes are two new functions:
- `WithTagUsingPattern`
- `WithNameUsingPattern`

**Comment by drnic** [comment]
@ArthurHlt thanks mate!
+1

**Comment by ArthurHlt** [comment]
Could I merge it?

**Pull request merged**
